Azure 204/Udemy/04-Develop Azure as Platform Service/Lesson13 Azure App Configuration/FeatureApp/FeatureApp/Models/ErrorViewModel.cs
using System;

namespace FeatureApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Azure 204/Udemy/04-Develop Azure as Platform Service/Lesson13 Azure App Configuration/FeatureApp/FeatureApp/Models/FeatureFlag.cs
namespace FeatureApp.Models
{
    public enum FeatureFlag
    {
        Staging = 1
    }
}

Azure 204/Udemy/04-Develop Azure as Platform Service/Lesson13 Azure App Configuration/FeatureApp/FeatureApp/Controllers/FeatureController.cs
using FeatureApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.FeatureManagement;
using Microsoft.FeatureManagement.Mvc;

namespace FeatureApp.Controllers
{
    public class FeatureController : Controller
    {
        private readonly IFeatureManager _featureManager;
        public FeatureController(IFeatureManager featureManager) 
        {
            _featureManager = featureManager;
        }

        [FeatureGate(FeatureFlag.Staging)]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Azure 204/Udemy/04-Develop Azure as Platform Service/Lesson13 Azure App Configuration/FeatureApp/FeatureApp/Controllers/HomeController.cs
using FeatureApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FeatureApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Azure 204/Udemy/04-Develop Azure as Platform Service/Lesson13 Azure App Configuration/FeatureApp/FeatureApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FeatureApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FeatureApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <feature name="staging">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Feature" asp-action="Index">Feature Option</a>
                            </li>
                        </feature>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FeatureApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>